---
# tasks file for mytomrole
- name: install java8 on linux2
  yum:
     name: java-1.8.0
     state: present
   
- name: install tomcat
  yum:
     name: tomcat
     state: present

- name: copy tomcat_conf file
  template:
     src: templates/tom_conf.j2
     dest: /usr/share/tomcat/conf/tomcat.conf

- name: install admin packages
  yum:
     name: "{{item}}"
     state: present
  with_items:
     - tomcat-webapps
     - tomcat-admin-webapps 

- name: copy tom_xml file
  template:
     src: templates/tom_xml.j2
     dest: /usr/share/tomcat/conf/tomcat-users.xml

- name: starting tomcat
  service:
     name: tomcat
     state: started
