---
# tasks file for tomrole
  name: install tomcat on Apache2
  yum: 
    name: tomcat 
    state: present

  name: replacing tomcat conf file using jinja2
  template:
    src: /templates/tomcat-conf.j2
    dest: /usr/share/tomcat/conf/tomcat.conf     
   
  name: Installing webapps & admin webapps for tomcat
  yum:
    name: {{"item"}}

  with_item: 
    name: tomcat-webapps
    name: tomcat-admin-webapps

  name: Replacing .xml file
  template:
    src: /templates/tomcat-users.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml       

  service:
    name: tomcat
    state: started


